### ISSUE TITLE
Checking internet connection keep failing

### ISSUE THREAD

**Issue by dongseok0** [OneEducation/connect#20]
When try to check internet connection with http://www.wikipedia.com, it response to redirect to https://www.wikipedia.org. And it's regarded as test failed. Wikipedia's response is changed. =() 

Fix: dbdeac595435123611766d193e19008df74b429f
1. Change url to https://www.wikipedia.org
    - Disable SSLv3 : 53a9e0fb4384ad9c18bc0c0decdf17731341d3c3
     ( http://stackoverflow.com/questions/26633349/disable-ssl-as-a-protocol-in-httpsurlconnection )
2. Regard 301 as success case.

**Comment by dongseok0** [comment]
dbdeac595435123611766d193e19008df74b429f

**Comment by nirajnakrani** [comment]
I have verified this fix and now the phase 2 check on connection to internet is successful means it properly resolves to https://www.wikipedia.org url. I have also verified that the upgrade scenario and it successfully upgrades to previous version. 

I have observed the below issue, not sure if it is regression of this fix:
1. Failure Scenario, when the wrong proxy detail is entered by the user(wrong user credential or wrong hostname/port detail), it doesnt not highlight the box in RED after hitting BACK button.
1. After successful upgrade of the apps, the internet stops working(fails with invalid proxy credential). But if you reset(OFF-ON) the wifi from the Connect app, it work without any issue.

**Comment by dongseok0** [comment]
1. Every exceptions are SSLException since I changed http -> https, so it couldn't be specified. To fix it, I    reverted https -> http. Then, wikipedia will response 301 code to redirect to https, and we can just regard it as successful case of connect to internet. - eabd4144c08bae917130efa56f309c0affb09a35
2. Attach package replace broadcast receiver to start proxy service when upgrade. - 25ffe7eeac220e93e6fbf442ba99abef72e7b6f0

**Comment by nirajnakrani** [comment]
Verified and its now working. You can merge the code and release it
